# Generated by Django 3.1.7 on 2022-01-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_name', models.CharField(default='', max_length=255)),
                ('main_presentation_text', models.TextField(default='')),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('is_open_to_work', models.BooleanField(default=False)),
                ('phone_number', models.CharField(default='', max_length=255)),
                ('repository_project_url', models.URLField(default='')),
                ('developer_email', models.EmailField(default='', max_length=254)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
