# Generated by Django 3.1.7 on 2022-01-30 12:36

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_siteconfiguration_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Tech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('proccessPorcent', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=255)),
                ('iconClassName', models.CharField(max_length=255)),
                ('link', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Technologie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_logo', models.ImageField(blank=True, null=True, upload_to=api.models.uploadTechPath)),
            ],
        ),
    ]
