# Generated by Django 3.1.7 on 2022-01-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_curriculum_project_projectitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repositoryUrl',
            field=models.URLField(default=''),
        ),
    ]
