# Generated by Django 3.1.7 on 2022-02-01 15:52

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_project_repositoryurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TechnologieItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='repositoryUrl',
            field=models.URLField(default='', null=True),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('is_currently_working', models.BooleanField(default=False)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to=api.models.uploadExperiencePath)),
                ('job_rol', models.CharField(max_length=255)),
                ('conmpany_name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('key_experiences', models.ManyToManyField(related_name='experiences_key', to='api.KeyExperience')),
                ('techs', models.ManyToManyField(related_name='experiences_items', to='api.TechnologieItem')),
            ],
        ),
    ]
