# docker-compose run backend  python backend/manage.py createsuperuser     
# docker-compose run backend  python backend/manage.py populate_database     
# docker-compose run backend  python backend/manage.py clean_database
     
version: "3"

services: 
  backend:
    build: ./backend
    ports: 
      - "5000:5000"
    volumes: 
      - ./backend:/backend
    command: >
      sh -c "cd ./backend/ &&
             python manage.py wait_for_db && 
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:5000"
    env_file:
      - ./.env
    depends_on: 
      - db

  db:
    image: postgres:10-alpine3.14
    env_file:
      - ./.env

  frontend:
    depends_on: 
      - backend
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true