# Generated by Django 3.1.7 on 2022-05-01 16:36

from django.db import migrations, models
import main_settings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], max_length=2)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_name', models.CharField(default='', max_length=255)),
                ('years_of_experience', models.FloatField(default=0.0)),
                ('is_open_to_work', models.BooleanField(default=False)),
                ('phone_number', models.CharField(default='', max_length=255)),
                ('repository_project_url', models.URLField(default='')),
                ('developer_email', models.EmailField(default='', max_length=254)),
                ('profilePicture', models.ImageField(blank=True, null=True, upload_to=main_settings.models.uploadProfilePath)),
                ('main_presentations', models.ManyToManyField(related_name='site_config_presentations', to='main_settings.TranslationText')),
                ('title_presentations', models.ManyToManyField(related_name='site_config_titles', to='main_settings.TranslationText')),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
