# Generated by Django 3.1.7 on 2022-04-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='years_of_experience',
            field=models.FloatField(default=0.0),
        ),
    ]
