# Generated by Django 3.1.7 on 2022-04-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_settings', '0002_auto_20220423_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='title_presentations',
            field=models.ManyToManyField(related_name='site_config_titles', to='main_settings.TranslationText'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='main_presentations',
            field=models.ManyToManyField(related_name='site_config_presentations', to='main_settings.TranslationText'),
        ),
    ]
