# Generated by Django 3.1.7 on 2022-05-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='name',
            field=models.CharField(choices=[('Modern', 'Modern'), ('Simple', 'Simple')], default='Modern', max_length=255),
        ),
    ]
