export const MAIN_TECHS = {
  REQUEST_SEND: "MAIN_TECHS_REQUEST_SEND",
  ERROR_SEND: "MAIN_TECHS_ERROR_SEND",
  SUCCESS_SEND: "MAIN_TECHS_SUCCESS_SEND",
  RESET: "MAIN_TECHS_RESET",
};

export const TECHS_ICONS = {
  REQUEST_SEND: "TECHS_ICONS_REQUEST_SEND",
  ERROR_SEND: "TECHS_ICONS_ERROR_SEND",
  SUCCESS_SEND: "TECHS_ICONS_SUCCESS_SEND",
  RESET: "TECHS_ICONS_RESET",
};
