const MAIN_TECHS = {
  REQUEST_SEND: "MAIN_TECHS_REQUEST_SEND",
  ERROR_SEND: "MAIN_TECHS_ERROR_SEND",
  SUCCESS_SEND: "MAIN_TECHS_SUCCESS_SEND",
  RESET: "MAIN_TECHS_RESET",
};

export default MAIN_TECHS;
