# Generated by Django 3.1.7 on 2022-05-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_settings', '0001_initial'),
        ('technologie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_tech',
            name='text',
        ),
        migrations.AddField(
            model_name='main_tech',
            name='texts',
            field=models.ManyToManyField(related_name='main_techs', to='main_settings.TranslationText'),
        ),
    ]
