# Generated by Django 3.1.7 on 2022-05-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologie', '0002_auto_20220502_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologie',
            name='icon_class',
            field=models.CharField(default='', max_length=255),
        ),
    ]
