# Generated by Django 3.1.7 on 2022-05-01 17:14

from django.db import migrations, models
import experience.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technologie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('is_currently_working', models.BooleanField(default=False)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to=experience.models.uploadExperiencePath)),
                ('job_rol', models.CharField(max_length=255)),
                ('conmpany_name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('key_experiences', models.ManyToManyField(related_name='experiences_key', to='experience.KeyExperience')),
                ('techs', models.ManyToManyField(related_name='experiences_items', to='technologie.TechnologieItem')),
            ],
        ),
    ]
