# Generated by Django 3.1.7 on 2022-05-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_settings', '0001_initial'),
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='conmpany_name',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='description',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='job_rol',
        ),
        migrations.AddField(
            model_name='experience',
            name='conmpany_names',
            field=models.ManyToManyField(related_name='expertise_company_names', to='main_settings.TranslationText'),
        ),
        migrations.AddField(
            model_name='experience',
            name='descriptions',
            field=models.ManyToManyField(related_name='expertise_descriptions', to='main_settings.TranslationText'),
        ),
        migrations.AddField(
            model_name='experience',
            name='job_rols',
            field=models.ManyToManyField(related_name='expertise_job_rols', to='main_settings.TranslationText'),
        ),
        migrations.AddField(
            model_name='experience',
            name='locations',
            field=models.ManyToManyField(related_name='expertise_locations', to='main_settings.TranslationText'),
        ),
    ]
