# Generated by Django 3.1.7 on 2022-05-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologie', '0001_initial'),
        ('main_settings', '0001_initial'),
        ('experience', '0002_auto_20220501_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='conmpany_names',
            field=models.ManyToManyField(blank=True, related_name='expertise_company_names', to='main_settings.TranslationText'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='descriptions',
            field=models.ManyToManyField(blank=True, related_name='expertise_descriptions', to='main_settings.TranslationText'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='job_rols',
            field=models.ManyToManyField(blank=True, related_name='expertise_job_rols', to='main_settings.TranslationText'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='key_experiences',
            field=models.ManyToManyField(blank=True, related_name='experiences_key', to='experience.KeyExperience'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='expertise_locations', to='main_settings.TranslationText'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='techs',
            field=models.ManyToManyField(blank=True, related_name='experiences_items', to='technologie.TechnologieItem'),
        ),
    ]
